### ISSUE TITLE
Quick question about implementation

### ISSUE THREAD

**Issue by hkoosha** [lucaoli/Hantek#2]
Hi!

First of all, thanks for developing this super awesome tool! I was able to write a cli based on it (published under GPL of course, just as this original work), you can find it here: https://github.com/hkoosha/hanteker#original-work

I had a quick question though: did you reverse engineer the Hantek protocol? or there's some documentation on it available somewhere?

**Comment by lucaoli** [comment]
Hi,

I'm happy you like my work!

Unfortunatelly I haven't found any documentation, I've done a reverse 
engineer job using the official windows tool and Wireshark usb capture 
feature to try to guess the commands.

Il 07/04/22 15:32, Koosha ha scritto:

**Comment by hkoosha** [comment]
Wow, then I should say you're super awesome :D
